version: '3.3'

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    ports:
      - "49153:80" # Web-UI Port
    volumes:
      - "/var/lib/docker/volumes/filebrowser_data:/srv" # Volume Port for direct file access => root.SFTP / root.FTP
