version: '3.3'

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    ports:
      - "8030:80" # Web-UI Port
    volumes:
      - "/dir/to/store/data:/srv" # This location will store all the data
